name = THMI

# Internal Log4j events
status = error
dest = err

# Sentry Appender
appender.sentry.type = Sentry
appender.sentry.name = Sentry

# Update your loggers to use Sentry
# App Logger - add Sentry appender reference
logger.app.appenderRef.sentry.ref = Sentry

# Root Logger - add Sentry appender reference
rootLogger.appenderRef.sentry.ref = Sentry

# Properties
property.logDir = /var/log/app
property.logFile = events.log
property.logPattern = %date{ISO8601}|%level|%thread|%logger{1}|%X{correlationId}|%X{projectId}|%message%n

# LogToConsole
appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = ${logPattern}

# LogToRollingFile
appender.rolling.type = RollingFile
appender.rolling.name = LogToRollingFile
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = ${logPattern}
appender.rolling.fileName = ${logDir}/${logFile}
appender.rolling.filePattern = ${logDir}/$${date:yyyy-MM}/events-%d{yyyy-MM-dd}-%i.log.gz
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 10MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 10

# App Logger
logger.app.name = com.thmi
logger.app.level = info
logger.app.additivity = false
logger.app.appenderRef.console.ref = LogToConsole
logger.app.appenderRef.rolling.ref = LogToRollingFile

# Default Logger
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = LogToConsole

# EmvFile
appender.emv.type = RollingFile
appender.emv.name = EmvFile
appender.emv.layout.type = PatternLayout
appender.emv.layout.pattern = ${logPattern}
appender.emv.fileName = ${logDir}/events.emv.log
appender.emv.filePattern = ${logDir}/$${date:yyyy-MM}/events-%d{yyyy-MM-dd}-%i.emv.log.gz
appender.emv.policies.type = Policies
appender.emv.policies.time.type = TimeBasedTriggeringPolicy
appender.emv.policies.size.type = SizeBasedTriggeringPolicy
appender.emv.policies.size.size = 10MB
appender.emv.strategy.type = DefaultRolloverStrategy
appender.emv.strategy.max = 10

# EMV Logger
logger.emv.name = com.thmi.thirdparty.emv
logger.emv.level = debug
logger.emv.additivity = false
logger.emv.appenderRef.rolling.ref = EmvFile

