services:
  engine:
    image: ghcr.io/cybermental/thmi/engine:2026.1.2-1799
    container_name: engine
    ports:
      - '9901:8080' # HTTP API
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/engine:/var/log/app
      - ./.logs/engine/tomcat:/usr/local/tomcat/logs
      - ./conf/engine:/etc/app
    networks:
      - dev

  history:
    image: ghcr.io/cybermental/thmi/history:2026.1.2-1799
    container_name: history
    ports:
      - '9902:8080' # HTTP API
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/history:/var/log/app
      - ./.logs/history/tomcat:/usr/local/tomcat/logs
      - ./conf/history:/etc/app
    networks:
      - dev
    depends_on:
      - engine

  hmi:
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT} -Djavax.xml.accessExternalDTD=all
    image: ghcr.io/cybermental/thmi/hmi:2026.1.2-1799
    container_name: hmi
    ports:
      - '9903:8080' # HTTP API
    volumes:
      - ./.logs/hmi:/var/log/app
      - ./.logs/hmi/tomcat:/usr/local/tomcat/logs
      - ./conf/hmi:/etc/app
    networks:
      - dev
    depends_on:
      - engine

  portal:
    image: ghcr.io/cybermental/thmi/portal:2026.1.2-1799
    container_name: portal
    ports:
      - '9906:8080' # HTTP API
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/portal:/var/log/app
      - ./.logs/portal/tomcat:/usr/local/tomcat/logs
      - ./conf/portal:/etc/app
    networks:
      - dev
    depends_on:
      - engine

networks:
  dev:
    name: dev
