services:
  engine:
    image: ghcr.io/cybermental/thmi/engine:2026.1.2-1799
    container_name: engine
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/engine:/var/log/app
      - ./.logs/engine/tomcat:/usr/local/tomcat/logs
      - ./conf/engine:/etc/app
    networks:
      - thmi-com

  history:
    image: ghcr.io/cybermental/thmi/history:2026.1.2-1799
    container_name: history
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/history:/var/log/app
      - ./.logs/history/tomcat:/usr/local/tomcat/logs
      - ./conf/history:/etc/app
    networks:
      - thmi-com
    depends_on:
      - engine

  hmi:
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT} -Djavax.xml.accessExternalDTD=all
    image: ghcr.io/cybermental/thmi/hmi:2026.1.2-1799
    container_name: hmi
    volumes:
      - ./.logs/hmi:/var/log/app
      - ./.qlogs/hmi/tomcat:/usr/local/tomcat/logs
      - ./conf/hmi:/etc/app
    networks:
      - thmi-com
    depends_on:
      - engine

  portal:
    image: ghcr.io/cybermental/thmi/portal:2026.1.2-1799
    container_name: portal
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/portal:/var/log/app
      - ./.logs/portal/tomcat:/usr/local/tomcat/logs
      - ./conf/portal:/etc/app
    networks:
      - thmi-com
    depends_on:
      - engine

networks:
  thmi-com:
    name: thmi-com
