services:
  engine:
    image: ghcr.io/cybermental/emc/engine:eval
    container_name: engine
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/engine:/var/log/app
      - ./.logs/engine/tomcat:/usr/local/tomcat/logs
      - ./conf/engine:/etc/app
    networks:
      - thmi-com

  history:
    image: ghcr.io/cybermental/emc/history:eval
    container_name: history
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/history:/var/log/app
      - ./.logs/history/tomcat:/usr/local/tomcat/logs
      - ./conf/history:/etc/app
    networks:
      - thmi-com
    depends_on:
      - engine

  hmi:
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT} -Djavax.xml.accessExternalDTD=all
    image: ghcr.io/cybermental/emc/hmi:eval
    container_name: hmi
    volumes:
      - ./.logs/hmi:/var/log/app
      - ./.logs/hmi/tomcat:/usr/local/tomcat/logs
      - ./conf/hmi:/etc/app
    networks:
      - thmi-com
    depends_on:
      - engine

  portal:
    image: ghcr.io/cybermental/emc/portal:eval
    container_name: portal
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs/portal:/var/log/app
      - ./.logs/portal/tomcat:/usr/local/tomcat/logs
      - ./conf/portal:/etc/app
    networks:
      - thmi-com
    depends_on:
      - engine

  nginx:
    image: ghcr.io/cybermental/emc/nginx-fe:eval
    container_name: nginx
    networks:
      - thmi-com
    restart: always
    environment:
      EXTERNAL_ADDRESS:
      GOOGLE_MAPS_API_KEY: ""
      MAPTILER_API_KEY: ""

    command: |
      /bin/bash -c " 
      envsubst '$${GOOGLE_MAPS_API_KEY} $${MAPTILER_API_KEY}' < /etc/nginx/conf.d/common.thirdparty.locations.template > /etc/nginx/conf.d/common.thirdparty.locations.conf 
      envsubst '$${EXTERNAL_ADDRESS}' < /var/www/thmi/portal/config.js.template >/var/www/thmi/portal/config.js && \
      envsubst '$${EXTERNAL_ADDRESS}' < /var/www/thmi/hmi/config.json.template > /var/www/thmi/hmi/config.json && \
      envsubst '$${EXTERNAL_ADDRESS}' < /etc/nginx/conf.d/hmi.locations.conf.template > /etc/nginx/conf.d/hmi.locations.conf && \
      nginx -g 'daemon off;'"

    ports:
      - 80:80 # web ui
      - 88:88 # engine
      - 1883:1883 # MQTT
    depends_on:
      - portal
      - hmi
      - engine

networks:
  thmi-com:
    name: thmi-com
