services:

  mariadb_edge:
    image: mariadb:10.6.7
    container_name: mariadb_edge
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=256M --init-file /data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=scada
    volumes:
      - mariadb_edge-volume:/var/lib/mysql
      - .logs/mariadb:/var/log/mysql
      - ./conf/mariadb/conf.d/common.cnf:/etc/mysql/conf.d/common.cnf:ro
      - ./conf/mariadb/conf.d/encryption.cnf:/etc/mysql/conf.d/encryption.cnf:ro
      - ./conf/mariadb/encryption:/etc/mysql/encryption:ro
      - ./conf/mariadb/init/init.sql:/data/application/init.sql:ro
    networks:
      - edge-net

  edge:
    image: ghcr.io/cybermental/emc/thmi-edge:eval
    container_name: edge
    ports:
      - '18080:8080'
    volumes:
      - ./.logs:/var/log/app
      - ./conf/edge/app_config.xml:/etc/app/app_config.xml
      - ./conf/edge/logging.properties:/etc/app/logging.properties
    networks:
      - edge-net
    depends_on:
      - mariadb_edge

volumes:
  mariadb_edge-volume:
    name: mariadb_edge-volume

networks:
  edge-net:
    name: edge-net
