services:

  edge:
    image: edge
    container_name: edge
    ports:
      - '9907:8080' # HTTP API
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.thmi.ENVIRONMENT=${CLOUD_ENVIRONMENT}
    volumes:
      - ./.logs:/var/log/app
      - ./conf/edge/app_config.xml:/etc/app/app_config.xml
      - ./conf/edge/logging.properties:/etc/app/logging.properties
    networks:
      - dev

networks:
  dev:
    name: dev
