name = THMI

# Internal Log4j events
status = error
dest = err

# Properties
property.logDir = /var/log/app
property.logFile = events.log
property.logPattern = %date{ISO8601}|%level|%thread|%logger{1}|%X{correlationId}|%X{projectId}|%message%n

# LogToConsole
appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = ${logPattern}

# LogToRollingFile
appender.rolling.type = RollingFile
appender.rolling.name = LogToRollingFile
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = ${logPattern}
appender.rolling.fileName = ${logDir}/${logFile}
appender.rolling.filePattern = ${logDir}/$${date:yyyy-MM}/events-%d{yyyy-MM-dd}-%i.log.gz
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 10MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 10

# App Logger
logger.app.name = com.thmi
logger.app.level = debug
logger.app.additivity = false
logger.app.appenderRef.console.ref = LogToConsole
logger.app.appenderRef.rolling.ref = LogToRollingFile

# Default Logger
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = LogToConsole
